# Generated by Django 3.2.24 on 2024-03-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_reason',
            field=models.CharField(choices=[('', 'Reason of Contact'), ('ORDER', 'Order'), ('SUGGESTIONS', 'Suggestions'), ('OTHER', 'Other')], max_length=24),
        ),
    ]
