# Generated by Django 3.2.24 on 2024-03-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
